#################################################################
# Note: you have to build h5py-mpi yourself
# 		if you want none mpi verstion add this to dependencies: - h5py=2.5.0
#
# * First, make sure you have openmpi and mpicc in your path
#
# * Download hdf5 source, then build hdf5-parrallel
# 		export CC=/gcc/4.9.1/bin/mpicc
# 		./configure --prefix=/path/to/parallel/hdf5 --enable-parallel --enable-shared
# 		make
# 		make check
# 		make install
#
# * source activate ai
# * pip install mpi4py
# * Git clone h5py, then build h5py:
# 		export CC=/gcc/4.9.1/bin/mpicc
#		python setup.py configure --mpi --hdf5=/path/to/parallel/hdf5
#		python setup.py build
#		python setup.py install
#################################################################

name: ai_dcase
channels:
  - https://conda.anaconda.org/trung # multiprocessing-logging, pysoundfile, sidekit
  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/numba # numba
  - https://conda.anaconda.org/r # r
  - defaults
dependencies:
  - python=2.7
  
  # scienctific computing
  - numpy=1.11.1
  - scipy=0.17.1
  - matplotlib
  - seaborn # visualization
  - pandas
  - sympy
  - nose
  - numba
  - nltk

  # interactive ipython and notebook
  - ipython
  - jupyter
  - notedown #convert markdown to ipynb
  - ipywidgets=5.2.2

  # speech processing
  - libsamplerate
  - pysoundfile # read sph audio file python

  # graphic processing
  # - opencv

  # deep learning api
  # - pycuda
  # - pygpu
  - theano
  - pymc

  # data science tools
  - pymc
  - scikit-learn=0.17

  # data management
  - h5py=2.6.0 # create dataset
  - pytables
  - pymongo
  - mongoengine
  - pyyaml
  - lxml
  - openpyxl # read excel
  - xlwt # create excel

  - pip:
    - pyparsing==1.5.7
    - pydot==1.0.28
    - librosa